name = "trio-comms"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "purebrain-referrals"
database_id = "cdd9a522-f947-42a6-b9a3-c30534e02c3f"

