name = "investor-avatar-proxy"
main = "worker.js"
compatibility_date = "2024-09-25"
account_id = "d526a3e9498dd167509003004df03290"

workers_dev = true

routes = [
  { pattern = "investor-api.purebrain.ai/*", zone_id = "49400cad1527af716705f6cb8c22bb65" }
]

[vars]
ALLOWED_ORIGIN = "https://purebrain.ai"
