name = "puresurf-api-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "d526a3e9498dd167509003004df03290"

# Route: all requests to purebrain.ai/api/surf/* hit this worker
# The zone_id is for purebrain.ai
[[routes]]
pattern = "purebrain.ai/api/surf/*"
zone_id = "49400cad1527af716705f6cb8c22bb65"
