name = "ara-index"
main = "src/worker.js"
compatibility_date = "2026-01-01"
usage_model = "unbound"

[[d1_databases]]
binding = "DB"
database_name = "ara-index"
database_id = "42163262-1849-4375-b10d-97a504f5d220"

[vars]
CORS_ORIGIN = "https://purebrain.ai"
TELEGRAM_CHAT_ID = "548906264"
