name = "blog-publisher"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "purebrain-social"
database_id = "625dde70-0a60-45e7-bf81-e18e5ac4d854"
