-- ============================================================================
-- SUPERSEDED — DO NOT APPLY
-- ============================================================================
--
-- The forward migration 0002-v1-sprint-schema.sql was split on 2026-05-07
-- into 0002a (referrals-only) + 0002b (clients additions, held).
-- This rollback file is therefore obsolete.
--
-- USE THIS INSTEAD:
--
--   0002a-referrals-only-schema.rollback.sql
--     - Rolls back 0002a-referrals-only-schema.sql
--     - Target: purebrain-referrals D1
--
-- 0002b has not been applied so no rollback exists yet.
--
-- ============================================================================
