-- ============================================================================
-- SUPERSEDED — DO NOT APPLY
-- ============================================================================
--
-- This migration was split on 2026-05-07 into two files due to a constitutional
-- domain-isolation violation: the clients table currently lives in purebrain-social
-- D1 (drift), and per the May 7 rule, purebrain-social must NEVER touch
-- referrals/clients. Applying this monolithic file would have required
-- cross-DB ALTERs that are now banned.
--
-- USE THESE INSTEAD:
--
--   0002a-referrals-only-schema.sql
--     - Applies to: purebrain-referrals D1
--     - Status: SAFE TO APPLY NOW
--     - Contains: partner_applications, rate_adjustments, payout_requests_v2,
--                 commission_payments column additions, referrals column additions,
--                 uniq_referrals_pbref_payment index, schema_migrations log
--
--   0002b-clients-additions.sql
--     - Applies to: purebrain-clients D1 (post-extraction)
--     - Status: 🔴 HELD — DO NOT APPLY YET
--     - Contains: clients column additions (previous_monthly_amount,
--                 plan_changed_at, is_support_tier)
--     - Apply only after clients extracted from purebrain-social per
--       constitutional domain-isolation rule.
--
-- This file is preserved as a marker. The 0002a + 0002b pair is the canonical
-- v1 sprint schema migration going forward.
--
-- ============================================================================
