"""
analytics_api.py — Reusable GA4 + Search Console API module
Generated by dept-systems-technology | 2026-03-03

Provides programmatic access to:
- Google Analytics 4 (property 525007539)
- Google Search Console (sc-domain:purebrain.ai)

Both use the existing service account:
  aether-drive-access@aether-integration.iam.gserviceaccount.com
  Key file: /home/jared/projects/AI-CIV/aether/.credentials/google-drive-service-account.json

Usage:
    from tools.analytics_api import ga4_report, gsc_query, get_ga4_summary

Requirements:
    google-auth (pip install google-auth)
    google-api-python-client (pip install google-api-python-client)
    requests
"""

import requests
import json
from datetime import datetime, timedelta
from google.oauth2 import service_account
from google.auth.transport.requests import Request as GoogleRequest

# ============================================================
# CONFIG
# ============================================================

SA_FILE = '/home/jared/projects/AI-CIV/aether/.credentials/google-drive-service-account.json'
GA4_PROPERTY_ID = '525007539'          # purebrain.ai GA4 property
GA4_ACCOUNT_ID = '384811174'           # PureBrain.ai GA4 account
GA4_MEASUREMENT_ID = 'G-86325WBT3P'   # Measurement ID (for reference only)
GSC_SITE_URL = 'sc-domain:purebrain.ai'

GA4_SCOPE = 'https://www.googleapis.com/auth/analytics.readonly'
GSC_SCOPE = 'https://www.googleapis.com/auth/webmasters.readonly'


# ============================================================
# TOKEN MANAGEMENT
# ============================================================

def _get_token(scope):
    """Get a fresh access token for the given Google API scope."""
    creds = service_account.Credentials.from_service_account_file(
        SA_FILE,
        scopes=[scope]
    )
    creds.refresh(GoogleRequest())
    return creds.token


def get_ga4_token():
    """Get GA4 read-only access token."""
    return _get_token(GA4_SCOPE)


def get_gsc_token():
    """Get Search Console read-only access token."""
    return _get_token(GSC_SCOPE)


# ============================================================
# GA4 DATA API
# ============================================================

def ga4_report(dimensions, metrics, date_range='30daysAgo', end_date='today',
               order_by_metric=None, order_desc=True, limit=25, filters=None):
    """
    Run a GA4 Data API report.

    Args:
        dimensions (list): List of dimension names, e.g. ['pagePath', 'sessionSource']
        metrics (list): List of metric names, e.g. ['sessions', 'totalUsers']
        date_range (str): Start date, e.g. '30daysAgo', '7daysAgo', '2026-02-01'
        end_date (str): End date, e.g. 'today', '2026-03-01'
        order_by_metric (str): Metric name to order by
        order_desc (bool): Descending order (default True)
        limit (int): Max rows to return
        filters (dict): Optional dimension or metric filter

    Returns:
        dict: Raw API response with 'rows', 'dimensionHeaders', 'metricHeaders'
    """
    token = get_ga4_token()
    headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
    url = f"https://analyticsdata.googleapis.com/v1beta/properties/{GA4_PROPERTY_ID}:runReport"

    payload = {
        "dateRanges": [{"startDate": date_range, "endDate": end_date}],
        "dimensions": [{"name": d} for d in dimensions],
        "metrics": [{"name": m} for m in metrics],
        "limit": limit
    }

    if order_by_metric:
        payload["orderBys"] = [{"metric": {"metricName": order_by_metric}, "desc": order_desc}]

    if filters:
        payload.update(filters)

    r = requests.post(url, headers=headers, json=payload)
    r.raise_for_status()
    return r.json()


def ga4_realtime():
    """Get realtime active users by page."""
    token = get_ga4_token()
    headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
    url = f"https://analyticsdata.googleapis.com/v1beta/properties/{GA4_PROPERTY_ID}:runRealtimeReport"
    payload = {
        "dimensions": [{"name": "unifiedScreenName"}],
        "metrics": [{"name": "activeUsers"}]
    }
    r = requests.post(url, headers=headers, json=payload)
    r.raise_for_status()
    return r.json()


def ga4_parse_rows(response):
    """
    Parse GA4 API response into list of dicts.

    Returns:
        list of dicts with dimension and metric values combined
    """
    rows_out = []
    dim_headers = [d['name'] for d in response.get('dimensionHeaders', [])]
    met_headers = [m['name'] for m in response.get('metricHeaders', [])]

    for row in response.get('rows', []):
        row_dict = {}
        for i, val in enumerate(row.get('dimensionValues', [])):
            row_dict[dim_headers[i]] = val['value']
        for i, val in enumerate(row.get('metricValues', [])):
            row_dict[met_headers[i]] = val['value']
        rows_out.append(row_dict)

    return rows_out


def get_ga4_summary(days=30):
    """
    Get a quick summary of GA4 data for the last N days.

    Returns:
        dict with sessions, users, pageviews, top pages, top channels
    """
    date_range = f'{days}daysAgo'

    # Overall metrics
    overview = ga4_report(
        dimensions=['sessionDefaultChannelGroup'],
        metrics=['sessions', 'totalUsers', 'newUsers', 'screenPageViews', 'bounceRate', 'averageSessionDuration'],
        date_range=date_range,
        order_by_metric='sessions'
    )

    # Top pages
    top_pages = ga4_report(
        dimensions=['pagePath'],
        metrics=['sessions', 'totalUsers', 'screenPageViews', 'bounceRate'],
        date_range=date_range,
        order_by_metric='sessions',
        limit=10
    )

    # Events
    events = ga4_report(
        dimensions=['eventName'],
        metrics=['eventCount', 'totalUsers'],
        date_range=date_range,
        order_by_metric='eventCount'
    )

    # Countries
    geo = ga4_report(
        dimensions=['country'],
        metrics=['sessions', 'totalUsers'],
        date_range=date_range,
        order_by_metric='sessions',
        limit=10
    )

    return {
        'period_days': days,
        'channels': ga4_parse_rows(overview),
        'top_pages': ga4_parse_rows(top_pages),
        'events': ga4_parse_rows(events),
        'countries': ga4_parse_rows(geo)
    }


# ============================================================
# GOOGLE SEARCH CONSOLE API
# ============================================================

def gsc_query(dimensions, start_date=None, end_date=None, days=28, limit=25):
    """
    Query Google Search Console search analytics.

    Args:
        dimensions (list): e.g. ['query'], ['page'], ['query', 'page'], ['country']
        start_date (str): e.g. '2026-02-01' (overrides days param)
        end_date (str): e.g. '2026-03-01'
        days (int): Days of lookback if start_date not specified
        limit (int): Max rows

    Returns:
        dict: Raw API response with 'rows'
    """
    token = get_gsc_token()
    headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
    url = f"https://www.googleapis.com/webmasters/v3/sites/{GSC_SITE_URL}/searchAnalytics/query"

    if not start_date:
        start_dt = datetime.now() - timedelta(days=days)
        start_date = start_dt.strftime('%Y-%m-%d')
    if not end_date:
        end_date = datetime.now().strftime('%Y-%m-%d')

    payload = {
        "startDate": start_date,
        "endDate": end_date,
        "dimensions": dimensions,
        "rowLimit": limit
    }

    r = requests.post(url, headers=headers, json=payload)
    r.raise_for_status()
    return r.json()


def gsc_parse_rows(response):
    """Parse GSC API response into list of dicts."""
    rows_out = []
    for row in response.get('rows', []):
        row_dict = {
            'clicks': row.get('clicks', 0),
            'impressions': row.get('impressions', 0),
            'ctr': row.get('ctr', 0),
            'position': row.get('position', 0)
        }
        keys = row.get('keys', [])
        if len(keys) == 1:
            row_dict['key'] = keys[0]
        else:
            for i, k in enumerate(keys):
                row_dict[f'key_{i}'] = k
        rows_out.append(row_dict)
    return rows_out


def gsc_list_sitemaps():
    """List all sitemaps and their indexing status."""
    token = get_gsc_token()
    headers = {'Authorization': f'Bearer {token}'}
    url = f"https://www.googleapis.com/webmasters/v3/sites/{GSC_SITE_URL}/sitemaps"
    r = requests.get(url, headers=headers)
    r.raise_for_status()
    return r.json()


def get_gsc_summary(days=28):
    """
    Get a quick Search Console summary.

    Returns:
        dict with top queries, top pages, totals
    """
    queries_raw = gsc_query(['query'], days=days, limit=20)
    pages_raw = gsc_query(['page'], days=days, limit=20)
    sitemaps = gsc_list_sitemaps()

    queries = gsc_parse_rows(queries_raw)
    pages = gsc_parse_rows(pages_raw)

    # Totals
    total_clicks = sum(q['clicks'] for q in queries)
    total_impressions = sum(q['impressions'] for q in queries)

    return {
        'period_days': days,
        'total_clicks': total_clicks,
        'total_impressions': total_impressions,
        'avg_ctr': total_clicks / total_impressions if total_impressions else 0,
        'top_queries': sorted(queries, key=lambda x: x['clicks'], reverse=True)[:10],
        'top_pages': sorted(pages, key=lambda x: x['clicks'], reverse=True)[:10],
        'sitemaps': sitemaps.get('sitemap', [])
    }


# ============================================================
# QUICK HEALTH CHECK
# ============================================================

def health_check():
    """
    Verify both GA4 and Search Console APIs are accessible.
    Returns True/False for each.
    """
    results = {}

    try:
        token = get_ga4_token()
        results['ga4_token'] = bool(token)
    except Exception as e:
        results['ga4_token'] = False
        results['ga4_error'] = str(e)

    try:
        r = ga4_report(['sessionDefaultChannelGroup'], ['sessions'], date_range='7daysAgo', limit=1)
        results['ga4_data'] = 'rows' in r
    except Exception as e:
        results['ga4_data'] = False
        results['ga4_data_error'] = str(e)

    try:
        token = get_gsc_token()
        results['gsc_token'] = bool(token)
    except Exception as e:
        results['gsc_token'] = False
        results['gsc_error'] = str(e)

    try:
        r = gsc_query(['query'], days=7, limit=1)
        results['gsc_data'] = True
    except Exception as e:
        results['gsc_data'] = False
        results['gsc_data_error'] = str(e)

    return results


# ============================================================
# MAIN — self-test
# ============================================================

if __name__ == '__main__':
    print("Analytics API Health Check")
    print("=" * 40)
    status = health_check()
    for k, v in status.items():
        print(f"  {k}: {v}")

    print()
    print("GA4 Quick Summary (7 days):")
    summary = get_ga4_summary(days=7)
    total_sessions = sum(int(c.get('sessions', 0)) for c in summary['channels'])
    total_users = sum(int(c.get('totalUsers', 0)) for c in summary['channels'])
    print(f"  Sessions: {total_sessions}")
    print(f"  Users: {total_users}")
    print(f"  Channels: {len(summary['channels'])}")
    print(f"  Top page: {summary['top_pages'][0].get('pagePath', 'N/A') if summary['top_pages'] else 'N/A'}")

    print()
    print("GSC Quick Summary (7 days):")
    gsc_sum = get_gsc_summary(days=7)
    print(f"  Clicks: {gsc_sum['total_clicks']}")
    print(f"  Impressions: {gsc_sum['total_impressions']}")
    if gsc_sum['top_queries']:
        print(f"  Top query: {gsc_sum['top_queries'][0].get('key', 'N/A')}")
