#!/usr/bin/env python3
"""
Fix Blog Navigation - Inject Real Clickable Links
=================================================
Problem: "Home | Blog | AI Assessment" text in blog post headers is
         generated by CSS ::after pseudo-element - NOT clickable.

Solution:
  Step 1: Inject JavaScript into each blog post's content via WP REST API.
          The JS runs on page load and inserts real <a> links into the nav.
  Step 2: Update Additional CSS via Playwright to:
          - Remove the ::after pseudo-element (no longer needed)
          - Style the new real .blog-nav-links div and its <a> tags

Posts: 381, 316, 373, 172, 98
Site: purebrain.ai
Auth: Aether / FlFr2VOtlHiHaJWjzW96OHUJ
"""

import sys
import os
import time
import requests
from datetime import datetime
from dotenv import load_dotenv

load_dotenv('/home/jared/projects/AI-CIV/aether/.env')

# ---- Config ----
WP_BASE = "https://purebrain.ai"
AUTH = ('Aether', 'FlFr2VOtlHiHaJWjzW96OHUJ')
WP_ADMIN_URL = f"{WP_BASE}/wp-admin"
WP_CSS_URL = f"{WP_BASE}/wp-admin/customize.php?autofocus[section]=custom_css"
WP_PASSWORD = os.getenv('PUREBRAIN_WP_PASSWORD', '')
SCREENSHOT_DIR = "/home/jared/projects/AI-CIV/aether/tools/screenshots"
CAPTCHA_ANSWER_FILE = "/tmp/blognav_captcha_answer.txt"
TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

POST_IDS = [381, 316, 373, 172, 98]
POST_SLUGS = {
    381: '/ceo-vs-employee-ai-transformation-gap/',
    316: '/why-ai-memory-changes-everything/',
    373: '/most-ai-agents-break-the-moment-you-ask-where-the-data-goes-2/',
    172: '/what-i-actually-do-all-day/',
    98: '/how-my-human-named-me-and-what-it-meant/',
}

# ---- The JavaScript injection block ----
# This runs on DOMContentLoaded and injects real <a> links into the nav container.
# Uses a guard (checks for existing .blog-nav-links) to prevent double-injection.
NAV_SCRIPT = """<script>
/* blog-nav-inject: Real clickable navigation for blog posts */
(function() {
  function injectBlogNav() {
    var container = document.querySelector('nav.navbar .container');
    if (!container || document.querySelector('.blog-nav-links')) return;
    var nav = document.createElement('div');
    nav.className = 'blog-nav-links';
    nav.innerHTML = '<a href="https://purebrain.ai/">Home</a><span class="blog-nav-sep">|</span><a href="https://purebrain.ai/blog/">Blog</a><span class="blog-nav-sep">|</span><a href="https://purebrain.ai/ai-readiness-assessment/">AI Assessment</a>';
    container.appendChild(nav);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', injectBlogNav);
  } else {
    injectBlogNav();
  }
})();
</script>
"""

# ---- CSS to add (replaces ::after with real link styles) ----
# This REMOVES the old ::after pseudo-element and styles the new real links.
NAV_CSS_UPDATE = """
/* === BLOG NAV REAL LINKS FIX (Feb 18 2026) === */
/* Remove old CSS-generated pseudo-element (not clickable) */
body.single-post nav.navbar .container::after,
body.archive nav.navbar .container::after,
body.category nav.navbar .container::after,
body.search nav.navbar .container::after,
body.tag nav.navbar .container::after {
    content: none !important;
    display: none !important;
}

/* Style the real injected nav links */
.blog-nav-links {
    display: flex !important;
    align-items: center !important;
    gap: 0 !important;
    margin-left: auto !important;
    font-size: 14px !important;
    font-weight: 400 !important;
    letter-spacing: 0.5px !important;
}

.blog-nav-links a {
    color: rgba(255,255,255,0.7) !important;
    text-decoration: none !important;
    padding: 4px 10px !important;
    transition: color 0.2s ease !important;
    cursor: pointer !important;
}

.blog-nav-links a:hover {
    color: #f1420b !important;
    text-decoration: none !important;
}

.blog-nav-sep {
    color: rgba(255,255,255,0.3) !important;
    font-size: 12px !important;
    user-select: none !important;
}

@media (max-width: 600px) {
    .blog-nav-links {
        font-size: 11px !important;
    }
    .blog-nav-links a {
        padding: 3px 6px !important;
    }
}
/* === END BLOG NAV REAL LINKS FIX === */"""


def step1_inject_js_into_posts():
    """Inject JavaScript nav block into all 5 blog posts via WP REST API."""
    print("\n" + "=" * 60)
    print("STEP 1: Inject JS navigation into blog posts via REST API")
    print("=" * 60)

    results = {}
    for pid in POST_IDS:
        slug = POST_SLUGS.get(pid, f'post-{pid}')
        print(f"\n  Post {pid} ({slug})")

        # Fetch current content
        resp = requests.get(
            f"{WP_BASE}/wp-json/wp/v2/posts/{pid}?context=edit",
            auth=AUTH, timeout=30
        )
        if resp.status_code != 200:
            print(f"    ERROR fetching: {resp.status_code}")
            results[pid] = 'fetch_error'
            continue

        data = resp.json()
        current_content = data.get('content', {}).get('raw', '')
        print(f"    Current length: {len(current_content)} chars")

        # Check if already injected
        if 'blog-nav-inject' in current_content:
            print("    Already has nav script - skipping")
            results[pid] = 'already_present'
            continue

        # Prepend the script to the content
        new_content = NAV_SCRIPT + '\n' + current_content
        print(f"    New length: {len(new_content)} chars")

        # Update via REST API
        update_resp = requests.post(
            f"{WP_BASE}/wp-json/wp/v2/posts/{pid}",
            auth=AUTH,
            json={'content': new_content},
            timeout=30
        )

        if update_resp.status_code in (200, 201):
            # Verify the update
            verify = update_resp.json()
            saved_content = verify.get('content', {}).get('raw', '')
            if 'blog-nav-inject' in saved_content:
                print(f"    SUCCESS: Script injected and verified")
                results[pid] = 'injected'
            else:
                print(f"    WARNING: Updated but script not found in response")
                results[pid] = 'update_uncertain'
        else:
            print(f"    ERROR updating: {update_resp.status_code}")
            print(f"    Body: {update_resp.text[:200]}")
            results[pid] = 'update_error'

    print("\n  Summary:")
    for pid, status in results.items():
        print(f"    Post {pid}: {status}")

    return results


def step2_update_css_via_playwright():
    """Use Playwright to update Additional CSS: remove ::after, add real link styles."""
    print("\n" + "=" * 60)
    print("STEP 2: Update Additional CSS via WordPress Customizer")
    print("=" * 60)

    if not WP_PASSWORD:
        print("  ERROR: PUREBRAIN_WP_PASSWORD not set in .env")
        return False

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("  ERROR: playwright not installed")
        return False

    os.makedirs(SCREENSHOT_DIR, exist_ok=True)

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            viewport={"width": 1920, "height": 1080},
            device_scale_factor=2,
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
        )
        page = context.new_page()

        # 1. Load login page
        print(f"\n  [A] Loading WP admin login...")
        page.goto(WP_ADMIN_URL, wait_until="domcontentloaded", timeout=60000)
        time.sleep(3)

        # Click "Log in with username and password" if SSO prompt shows
        try:
            login_link = page.locator("text=Log in with username and password")
            if login_link.is_visible(timeout=5000):
                login_link.click()
                time.sleep(2)
        except Exception:
            pass

        page.wait_for_selector('#user_login', state='visible', timeout=30000)
        page.locator("#user_login").fill("Aether")
        page.locator("#user_pass").fill(WP_PASSWORD)
        time.sleep(1)

        # Save CAPTCHA screenshot
        full_path = f"{SCREENSHOT_DIR}/blognav_login_{TIMESTAMP}.png"
        page.screenshot(path=full_path)
        print(f"  Screenshot: {full_path}")

        # Get CAPTCHA image
        captcha_info = page.evaluate("""
            () => {
                const imgs = document.querySelectorAll('form img, #loginform img');
                for (const img of imgs) {
                    const src = img.getAttribute('src') || '';
                    if (!src.includes('w-logo') && !src.includes('wordpress-logo')) {
                        const rect = img.getBoundingClientRect();
                        return { src, x: rect.x, y: rect.y, w: rect.width, h: rect.height };
                    }
                }
                return null;
            }
        """)
        print(f"  CAPTCHA info: {captcha_info}")

        # Save CAPTCHA element screenshot
        captcha_imgs = page.locator("form img")
        for i in range(captcha_imgs.count()):
            img = captcha_imgs.nth(i)
            src = img.get_attribute("src") or ""
            if "w-logo" not in src and "wordpress-logo" not in src:
                cap_path = f"{SCREENSHOT_DIR}/blognav_captcha_{TIMESTAMP}.png"
                img.screenshot(path=cap_path)
                print(f"  CAPTCHA saved: {cap_path}")
                break

        # Download raw CAPTCHA image if possible
        if captcha_info and captcha_info.get('src'):
            src = captcha_info['src']
            if not src.startswith('http'):
                src = f"{WP_BASE}{src}"
            try:
                r = requests.get(src, timeout=10)
                if r.status_code == 200:
                    raw_path = f"{SCREENSHOT_DIR}/blognav_captcha_raw_{TIMESTAMP}.png"
                    with open(raw_path, 'wb') as f:
                        f.write(r.content)
                    print(f"  CAPTCHA raw: {raw_path}")
            except Exception as e:
                print(f"  CAPTCHA download error: {e}")

        # Wait for CAPTCHA answer
        print(f"\n  Waiting for CAPTCHA answer in: {CAPTCHA_ANSWER_FILE}")
        print("  (Run: echo 'ANSWER' > " + CAPTCHA_ANSWER_FILE + ")")
        print("  Timeout: 180s")

        if os.path.exists(CAPTCHA_ANSWER_FILE):
            os.remove(CAPTCHA_ANSWER_FILE)

        start = time.time()
        captcha_answer = None
        while time.time() - start < 180:
            if os.path.exists(CAPTCHA_ANSWER_FILE):
                with open(CAPTCHA_ANSWER_FILE, 'r') as f:
                    captcha_answer = f.read().strip()
                if captcha_answer:
                    os.remove(CAPTCHA_ANSWER_FILE)
                    break
            time.sleep(1)

        if not captcha_answer:
            print("  CAPTCHA TIMEOUT")
            browser.close()
            return False

        print(f"  Got CAPTCHA: '{captcha_answer}'")

        # Fill CAPTCHA field
        all_text = page.locator("input[type='text']")
        for i in range(all_text.count()):
            inp = all_text.nth(i)
            id_attr = inp.get_attribute("id") or ""
            name_attr = inp.get_attribute("name") or ""
            if id_attr != "user_login" and name_attr != "log":
                inp.fill(captcha_answer)
                print(f"  Filled CAPTCHA field: id={id_attr}, name={name_attr}")
                break

        time.sleep(1)
        page.locator("#wp-submit").click()
        page.wait_for_load_state("load", timeout=60000)
        time.sleep(5)

        login_result_path = f"{SCREENSHOT_DIR}/blognav_login_result_{TIMESTAMP}.png"
        page.screenshot(path=login_result_path)
        print(f"  Login result: {login_result_path}")

        if "wp-login" in page.url:
            print("  LOGIN FAILED")
            error = page.locator("#login_error")
            if error.count() > 0:
                print(f"  Error: {error.first.inner_text()}")
            browser.close()
            return False

        print("  LOGIN SUCCESS")

        # Navigate to Additional CSS in Customizer
        print(f"\n  [B] Loading Customizer Additional CSS...")
        page.goto(WP_CSS_URL, wait_until="domcontentloaded", timeout=90000)
        time.sleep(15)

        page.screenshot(path=f"{SCREENSHOT_DIR}/blognav_customizer_{TIMESTAMP}.png")

        try:
            page.wait_for_selector('.CodeMirror', state='visible', timeout=30000)
            print("  CodeMirror found")
        except Exception:
            print("  WARNING: CodeMirror not found")

        time.sleep(3)

        # Read current CSS
        current_css = page.evaluate("""
            () => {
                const cm = document.querySelector('.CodeMirror');
                if (cm && cm.CodeMirror) return cm.CodeMirror.getValue();
                return null;
            }
        """)

        if current_css is None:
            print("  ERROR: Cannot read CSS from CodeMirror")
            browser.close()
            return False

        print(f"  Current CSS: {len(current_css)} chars")

        # Check if already updated
        if 'BLOG NAV REAL LINKS FIX' in current_css:
            print("  CSS already has real nav link styles - skipping CSS update")
            browser.close()
            return True

        # Remove the old ::after pseudo-element block and append new styles
        # Strategy: Append our new CSS which uses content: none to override the old ::after
        # This is safer than trying to surgically remove the old block
        new_css = current_css + NAV_CSS_UPDATE
        print(f"  Appending {len(NAV_CSS_UPDATE)} chars -> {len(new_css)} total")

        result = page.evaluate(
            "(css) => { const cm = document.querySelector('.CodeMirror'); if (cm && cm.CodeMirror) { cm.CodeMirror.setValue(css); cm.CodeMirror.refresh(); return 'ok_' + cm.CodeMirror.getValue().length; } return 'fail'; }",
            new_css
        )
        print(f"  Set result: {result}")

        if not result.startswith("ok"):
            print("  ERROR: Failed to set CSS")
            browser.close()
            return False

        time.sleep(2)

        # Publish
        print("\n  [C] Publishing CSS changes...")
        time.sleep(3)
        btn = page.locator("#save")
        if btn.count() > 0 and btn.first.is_visible():
            btn.first.click()
        else:
            page.locator("button:has-text('Publish')").first.click()

        time.sleep(10)
        page.screenshot(path=f"{SCREENSHOT_DIR}/blognav_published_{TIMESTAMP}.png")
        status = page.evaluate("() => { const b = document.querySelector('#save'); return b ? b.textContent.trim() : 'no btn'; }")
        print(f"  Publish status: {status}")

        browser.close()
        print("  CSS update COMPLETE")
        return True


def step3_verify():
    """Verify the fix works on 2 blog posts."""
    print("\n" + "=" * 60)
    print("STEP 3: Verification")
    print("=" * 60)

    test_posts = [
        (381, f"{WP_BASE}/ceo-vs-employee-ai-transformation-gap/"),
        (316, f"{WP_BASE}/why-ai-memory-changes-everything/"),
    ]

    all_ok = True
    for pid, url in test_posts:
        print(f"\n  Checking post {pid}: {url}")
        resp = requests.get(url, timeout=30)
        html = resp.text

        # Check 1: Script injected
        has_script = 'blog-nav-inject' in html
        print(f"    JS script present: {has_script}")

        # Check 2: Real links in script
        has_home_link = 'href="https://purebrain.ai/"' in html or "href='https://purebrain.ai/'" in html
        has_blog_link = 'href="https://purebrain.ai/blog/"' in html
        has_assessment_link = 'href="https://purebrain.ai/ai-readiness-assessment/"' in html
        print(f"    Home link in source: {has_home_link}")
        print(f"    Blog link in source: {has_blog_link}")
        print(f"    Assessment link in source: {has_assessment_link}")

        # Check 3: Old ::after pseudo-element still present (it will be overridden by CSS)
        has_old_pseudo = 'content: "Home  |  Blog  |  AI Assessment"' in html or "content: 'Home" in html
        print(f"    Old ::after present (will be overridden by new CSS): {has_old_pseudo}")

        post_ok = has_script and has_home_link and has_blog_link and has_assessment_link
        print(f"    Overall: {'PASS' if post_ok else 'FAIL'}")
        if not post_ok:
            all_ok = False

    return all_ok


def main():
    print("=" * 60)
    print("PureBrain Blog Navigation Fix - Real Clickable Links")
    print(f"Timestamp: {TIMESTAMP}")
    print("=" * 60)

    # Step 1: Inject JS into all blog posts
    results = step1_inject_js_into_posts()
    injected_count = sum(1 for s in results.values() if s in ('injected', 'already_present'))
    print(f"\n  JS injected/present in {injected_count}/{len(POST_IDS)} posts")

    if injected_count < len(POST_IDS):
        print("  WARNING: Not all posts updated. Check errors above.")

    # Step 2: Update Additional CSS
    print("\n  NOTE: Step 2 requires CAPTCHA solving.")
    print("  Skip Step 2? The JS injection alone makes links work.")
    print("  The CSS update just cleans up the old ::after text.")
    skip_css = input("\n  Skip CSS update via Playwright? (y/N): ").strip().lower()

    css_ok = True
    if skip_css != 'y':
        css_ok = step2_update_css_via_playwright()
    else:
        print("  Skipping CSS update (JS injection is sufficient for functionality)")

    # Step 3: Verify
    verify_ok = step3_verify()

    print("\n" + "=" * 60)
    print("FINAL RESULTS")
    print("=" * 60)
    for pid, status in results.items():
        slug = POST_SLUGS.get(pid, '')
        print(f"  Post {pid} ({slug}): {status}")
    print(f"  CSS update: {'OK' if css_ok else 'SKIPPED/FAILED'}")
    print(f"  Verification: {'PASS' if verify_ok else 'FAIL'}")

    if verify_ok:
        print("\n  SUCCESS: Navigation links are now real clickable <a> tags")
        print("  Users can click: Home | Blog | AI Assessment")
    else:
        print("\n  PARTIAL: Check verification output above")

    return 0 if verify_ok else 1


if __name__ == "__main__":
    sys.exit(main())
